---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        run: myweb
    spec:
      containers:
      - image: 172.17.109.86:5000/elhamahmadloo/myweb:1
        imagePullPolicy: Always
        name: myweb
---
apiVersion:v1
kind: Service
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  ports:
  - nodePort: 32328
    port: 80
    protocol:TCP
    targetPort: 80
  selector:
    app: myweb
  type: NodePort  
  
  

        
       
